name: Verify Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - 'deployments-*.json'

jobs:
  verify:
    if: startsWith(github.head_ref, 'deploy/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Verify deployment bytecode
        run: npx hardhat verify-deployment --network amoy
        env:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
